#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <new strapi api key>"
    exit 1
fi
NEW_API_KEY=$1

#Replace the Strapi API key in configuration files
docker exec -it $(docker ps | grep arsenalf-nginx | awk '{print $1}') sh -c "chmod -R a+rX /app"
docker exec -it $(docker ps | grep arsenalf-nginx | awk '{print $1}') sh -c "chmod +x /app/replace_strapi_api_key"
docker exec -it $(docker ps | grep arsenalf-nginx | awk '{print $1}') sh -c "/app/replace_strapi_api_key FOOGAZY_TOKEN $NEW_API_KEY /app"
docker exec -it $(docker ps | grep strapi:latest | awk '{print $1}') sh -c "npm run strapi import -- -f /opt/app/personal-website-strapi-export.tar.gz.enc"
docker exec -it $(docker ps | grep arsenalf-nginx | awk '{print $1}') sh -c "chmod -R a+rX /app"

# Obtain SSL certificates
docker exec -it $(docker ps | grep arsenalf-nginx | awk '{print $1}') sh -c "certbot certonly --webroot -w /app -d  cristian.pompey.linushome.com"

# Schedule automatic renewal of SSL certificates 
docker exec -it $(docker ps | grep arsenalf-nginx | awk '{print $1}') sh -c "SLEEPTIME=$(awk 'BEGIN{srand(); print int(rand()*(3600+1))}'); echo "0 0,12 * * * root sleep $SLEEPTIME && certbot renew -q" | sudo tee -a /etc/crontab > /dev/null"

docker exec $(docker ps | grep arsenalf-nginx | awk '{print $1}') sh -c "goaccess /var/log/nginx/access.log -o /app/report.html --log-format=COMBINED --real-time-html"
    